# git-cliff configuration
# https://git-cliff.org/docs/configuration

[changelog]
header = "# Changelog\n\n"
body = """
{% set repo = "https://github.com/tq-lang/tq" -%}
{% if version -%}
  ## [{{ version | trim_start_matches(pat="v") }}]({{ repo }}/releases/tag/{{ version }}) — {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
  ## Unreleased
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim }}
{% for commit in commits %}
  - {{ commit.message | split(pat="\n") | first | trim }} ([{{ commit.id | truncate(length=7, end="") }}]({{ repo }}/commit/{{ commit.id }}))
{%- endfor %}
{% endfor %}
"""
trim = true
footer = ""
postprocessors = [
  { pattern = '\(#([0-9]+)\)', replace = '([#${1}](https://github.com/tq-lang/tq/pull/${1}))' },
]

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^doc", group = "Docs" },
  { message = "^style", group = "Style" },
  { message = "^test", group = "Tests" },
  { message = "^build", group = "Build" },
  { message = "^ci", group = "CI" },
  { message = "^revert", group = "Reverts" },
  { message = '^chore\(changelog\)', skip = true },
  { message = "^chore", group = "Chores" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "newest"
