name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  attestations: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version: "1.24"

      - name: Install git-cliff
        uses: taiki-e/install-action@735e5933943122c5ac182670a935f54a949265c1 # v2
        with:
          tool: git-cliff

      - name: Install syft
        uses: taiki-e/install-action@735e5933943122c5ac182670a935f54a949265c1 # v2
        with:
          tool: syft

      - name: Create Homebrew tap app token
        id: homebrew_tap_app_token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2
        with:
          app-id: ${{ secrets.HOMEBREW_TAP_APP_ID }}
          private-key: ${{ secrets.HOMEBREW_TAP_APP_PRIVATE_KEY }}
          owner: tq-lang
          repositories: homebrew-tap

      - uses: goreleaser/goreleaser-action@9a127d869fb706213d29cdf8eef3a4ea2b869415 # v7
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ steps.homebrew_tap_app_token.outputs.token }}

      - name: Attest release archives
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3
        with:
          subject-path: |
            dist/*.tar.gz
            dist/*.zip
